### ISSUE TITLE
Sample does not correctly handle font style.

### ISSUE THREAD

**Issue by paulhoux** [chaoticbob/Cinder-SdfText#1]
Not sure if this is an issue with the sample or with FreeType, but it seems the font style (bold, italic, etc.) is not always applied correctly. For instance, compare `Arial` to `Arial Bold` or `Arial Italic`: there is no difference.

**Comment by chaoticbob** [comment]
It's an issue with the sample. I didn't add style information parsing yet.

**Comment by chaoticbob** [comment]
Should be fixed: https://github.com/chaoticbob/Cinder-SdfText/commit/17c1d80509de25db6bf62d64d778c4864ad7638b
