### ISSUE TITLE
Build Details

### ISSUE THREAD

**Issue by BorisKourt** [chaoticbob/Cinder-SdfText#18]
Hi, 

I am new to Cinder and really want to test this library out.

How do I add Freetype to sources in Visual Studio? When I open the project it looks for `freetype` alongside `gl` and `msdfgen`. But none of those files are available.

I downloaded the latest freetype source, but don't see anything in there that matches the source structure. 

I also tried installing the freetype package in Nuget, but I am still getting not found build errors.

Thank you for this awesome lib!

**Comment by chaoticbob** [comment]
Hi Boris,

Which branch of Cinder are you using?

**Comment by BorisKourt** [comment]
I am using a build of latest master. 0.9.1~

And to clarify: I cloned this project, opened the solution in VS and tried to build debug + release.

**Comment by chaoticbob** [comment]
Did you clone the project into the blocks directory within Cinder?

**Comment by BorisKourt** [comment]
Ah no, I opened it as its own project. Should I place it as a `block` in my project and then install freetype?

Edit: I didn't see a Block xml file in root of the repo and thought it was standalone.

**Comment by chaoticbob** [comment]
Ideally, you should place it within the blocks directory within the Cinder repo directory: https://github.com/cinder/Cinder/tree/master/blocks.

The reason it sort of has to be there, is that there isn't a good way in VisualStudio to tell a project where a lot of external files are. I'm trying to find a good way to get around this.

Cinder 0.9.x contains the FreeType source code. You could also just look at relative path for the FreeType files in the Cinder-SdfText project file and just copy the FreeType source there. A bit hacky.

**Comment by BorisKourt** [comment]
Is this the blocks directory in the cloned Cinder repo, the built Cinder directory, or is it the blocks directory in my Cinder project? 

If its in Cinder itself, do I need to rebuild all of Cinder once I have placed the new block? 

I haven't used a 'CinderBlock' yet (as is evident I am sure), wondering if this is the same process for a library like: https://github.com/cwhitney/PretzelGui ? 

Sorry, very new! The current docs only talk about Tinderbox. Which I assume I can't use once I already have a project created?

Thanks again!

**Comment by chaoticbob** [comment]
> Is this the blocks directory in the cloned Cinder repo, the built Cinder directory, or is it the blocks directory in my Cinder project?

The blocks directory in the cloned Cinder repo. 

> If its in cinder itself, do I need to rebuild all of cinder once I have placed the new block?

No, you shouldn't have to. Just need to build the block itself.

There are various ways to build Cinder blocks depending on what the blocks themselves make use of. We're working on a more universal way to handle blocks that is less confusing.

**Comment by BorisKourt** [comment]
Thanks for your patience, I hopefully have one last question. 

I built the SdfText block in the cinder directory. Do I now just copy them to my actual project to use? Or do I setup the project to look for them inside the Cinder directory?

**Comment by chaoticbob** [comment]
You can do it either way. The second way is a little less work if you want to continue pulling from the SdfText repo and just rebuilding. 

Are the samples working for you?

**Comment by BorisKourt** [comment]
I opened the Basic project and had to adjust the linker settings for it to find the latest SdfText build. 

After it found it though I get a different kind of error:

```
    Error LNK2019: unresolved external symbol "public: void __cdecl cinder::IStreamCinder::readLittle<char32_t>(char32_t *)" (??$readLittle@_U@IStreamCinder@cinder@@QEAAXPEA_U@Z) referenced in function "public: static class std::shared_ptr<class cinder::gl::SdfText> __cdecl cinder::gl::SdfText::load(class std::shared_ptr<class cinder::DataSource> const &,float)" (?load@SdfText@gl@cinder@@SA?AV?$shared_ptr@VSdfText@gl@cinder@@@std@@AEBV?$shared_ptr@VDataSource@cinder@@@5@M@Z)
```

Do you know where this is coming from?

**Comment by chaoticbob** [comment]
Are you building a Win32 or a x64 project?

**Comment by BorisKourt** [comment]
x64, built cinder and sdftext as x64. 

Should I switch everything to Win32?

**Comment by chaoticbob** [comment]
x64 should work. I can't think of a reason why that symbol should be missing.

Are you on VS2013 or VS2015?

**Comment by BorisKourt** [comment]
Win 10 and VS2015.  I had a LNK2019 issue a few days ago with a particular arity(?) of Surface::create that I couldn't find a solution to ether. Is it worth asking in main Cinder repo?

Forgot to note that there were two LNK2019 errors:

```
    Error LNK2019: unresolved external symbol "public: void __cdecl cinder::OStream::writeLittle<char32_t>(char32_t)" (??$writeLittle@_U@OStream@cinder@@QEAAX_U@Z) referenced in function "public: static void __cdecl cinder::gl::SdfText::save(class std::shared_ptr<class cinder::DataTarget> const &,class std::shared_ptr<class cinder::gl::SdfText> const &)" (?save@SdfText@gl@cinder@@SAXAEBV?$shared_ptr@VDataTarget@cinder@@@std@@AEBV?$shared_ptr@VSdfText@gl@cinder@@@5@@Z)

    Error LNK2019: unresolved external symbol "public: void __cdecl cinder::IStreamCinder::readLittle<char32_t>(char32_t *)" (??$readLittle@_U@IStreamCinder@cinder@@QEAAXPEA_U@Z) referenced in function "public: static class std::shared_ptr<class cinder::gl::SdfText> __cdecl cinder::gl::SdfText::load(class std::shared_ptr<class cinder::DataSource> const &,float)" (?load@SdfText@gl@cinder@@SA?AV?$shared_ptr@VSdfText@gl@cinder@@@std@@AEBV?$shared_ptr@VDataSource@cinder@@@5@M@Z)
```

**Comment by chaoticbob** [comment]
I made a fix that forces uint32_t instead of char32_t: https://github.com/chaoticbob/Cinder-SdfText/commit/5bae36c8d80e51f077f588b56b172b1d1720ff83. 

Give it a shot and see if it works. I am aware of some stuff on VS2015, but haven't spent a ton of time with it.

**Comment by BorisKourt** [comment]
Tested your version, it looks like the previous issue is gone! But I got the following:

```
Run-Time Check Failure #2 - Stack around the variable 'surface' was corrupted.
```

I would imagine that this relates to my previous Surface::create issue? Ill rebuild cinder to latest master and if that doesn't work I will put up an issue there. 

Thank you so much for your help!

**Comment by chaoticbob** [comment]
Right on. If you get it working, could you post to the thread on the forum and let me know. If you're still having issues with SdfText itself, feel free to make another issue here.

**Comment by BorisKourt** [comment]
I should probably list the call stack just in case:

```
>   Basic.exe!cinder::gl::SdfText::TextureAtlas::TextureAtlas(FT_FaceRec_ * face, const cinder::gl::SdfText::Format & format, const std::vector<unsigned int,std::allocator<unsigned int> > & glyphIndices) Line 357    C++
    Basic.exe!cinder::gl::SdfText::TextureAtlas::create(FT_FaceRec_ * face, const cinder::gl::SdfText::Format & format, const std::vector<unsigned int,std::allocator<unsigned int> > & glyphIndices) Line 361  C++
    Basic.exe!cinder::gl::SdfTextManager::getTextureAtlas(FT_FaceRec_ * face, const cinder::gl::SdfText::Format & format, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & utf8Chars, const std::vector<unsigned int,std::allocator<unsigned int> > & glyphIndices) Line 738    C++
    Basic.exe!cinder::gl::SdfText::SdfText(const cinder::gl::SdfText::Font & font, const cinder::gl::SdfText::Format & format, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & utf8Chars, bool generateSdf) Line 1333  C++
    Basic.exe!cinder::gl::SdfText::create(const cinder::gl::SdfText::Font & font, const cinder::gl::SdfText::Format & format, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & supportedChars) Line 1357    C++
    Basic.exe!cinder::gl::SdfText::create(const std::experimental::filesystem::v1::path & filePath, const cinder::gl::SdfText::Font & font, const cinder::gl::SdfText::Format & format, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & utf8Chars) Line 1368   C++
    Basic.exe!BasicApp::setup() Line 40 C++
    Basic.exe!cinder::app::AppBase::privateSetup__() Line 153   C++
    Basic.exe!cinder::app::AppImplMswBasic::run() Line 61   C++
    Basic.exe!cinder::app::AppMsw::launch() Line 93 C++
    Basic.exe!cinder::app::AppBase::executeLaunch() Line 134    C++
    Basic.exe!cinder::app::AppMsw::main<BasicApp>(const std::shared_ptr<cinder::app::Renderer> & defaultRenderer, const char * title, const std::function<void __cdecl(cinder::app::AppMsw::Settings *)> & settingsFn) Line 109 C++
    Basic.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 137    C++
    [External Code] 

```

**Comment by BorisKourt** [comment]
Will do! Thanks :)

**Comment by BorisKourt** [comment]
Hi @chaoticbob 

After rebuilding Cinder and SdfText with the latest versions, your samples work fine.

Thanks again for your help!

**Comment by chaoticbob** [comment]
Great! Thanks for letting me know!
