### ISSUE TITLE
Kerning / positioning is wobbly.

### ISSUE THREAD

**Issue by paulhoux** [chaoticbob/Cinder-SdfText#2]
I am sure this is on your TODO list, but text kerning and positioning is not precise enough, leading to low quality text layout. This is especially apparent when using small font sizes. Fonts in the following image are scaled up or down to make them appear roughly the same size, but the font size used to create the mesh is different.

![sdf_layout](https://cloud.githubusercontent.com/assets/304908/17155131/271d434a-5384-11e6-92ac-fbfa39daef93.png)

It's also clear that the two lines of text do not have the same height, even though they should roughly be the same.

**Comment by chaoticbob** [comment]
Hey Paul,
This is definitely on the TODO. Working out sorting through all the math for baselines and kerning. Curious, are you scaling this with just gl::scale or another way?

**Comment by paulhoux** [comment]
Yeah, it's a simple `gl::scale(...);` call before `drawStringWrapped()`.

**Comment by chaoticbob** [comment]
Let me know if this: https://github.com/chaoticbob/Cinder-SDF/commit/28c09acd28da3c1e9fdd27caf1d37539458e317c addresses this issue.

![sdf-006](https://cloud.githubusercontent.com/assets/379079/17165597/473038a2-5386-11e6-972a-70d13f185534.png)
