### ISSUE TITLE
measureString returns wrong size

### ISSUE THREAD

**Issue by gaborpapp** [chaoticbob/Cinder-SdfText#20]
size returned by`measureString` differs from the render size of `drawString`.

![sdftext-measurestring](https://cloud.githubusercontent.com/assets/203532/19073430/515cba76-8a3b-11e6-996e-e1273c3e6521.gif)

from the [forum](http://discourse.libcinder.org/t/cinder-sdftext-initial-release-wip/171/38)

**Comment by chaoticbob** [comment]
`measureString` should be fixed now. Also added `measureStringRect`: https://github.com/chaoticbob/Cinder-SdfText/blob/master/src/cinder/gl/SdfText.cpp#L2275.

`measureStringRect` returns the full bounds for the string - so if you add the baseline it should draw the rect in the correct place. There's a MeasureString samples to demonstrate this. 

There area few edge cases that aren't covered yet, such as fonts with long strokes.

**Comment by gaborpapp** [comment]
Great! Works nicely. Thanks!
