### ISSUE TITLE
PNG Ident not found

### ISSUE THREAD

**Issue by BorisKourt** [chaoticbob/Cinder-SdfText#25]
Hey, 

After a rebuild and update of all my blocks I am getting:

```
|fatal  | cinder::app::AppBase::executeLaunch[192] Uncaught exception, type: class cinder::Exception, what: PNG ident not found
```

I traced it to the file here: https://github.com/chaoticbob/Cinder-SdfText/blob/9933c6d1fa100e8bc3f3ace14b77f3038ce59fa9/src/cinder/gl/SdfText.cpp#L1914

But I am not sure how to fix this. 
What does this error mean?

Thanks!
Boris

**Comment by chaoticbob** [comment]
If you generated the cache with an older version of the code - it's not compatible with the more recent versions. We had to make a couple of adjustments to address some issues in the cacher. You can just delete the old caches and have it regenerate.

**Comment by BorisKourt** [comment]
Thanks! I should have realized!
