### ISSUE TITLE
Feature request: save and load fonts.

### ISSUE THREAD

**Issue by paulhoux** [chaoticbob/Cinder-SdfText#3]
Just ignore me if you had enough :) , but it would be great if we could save and load fonts, to speed up the generation of the textures. Before saving, an optimization might be applied to minimize texture space (e.g. use bin packing, see issue #4).

**Comment by chaoticbob** [comment]
Keep 'em coming! :)

This is definitely on the TODO list.

**Comment by chaoticbob** [comment]
Save/load functionality has been added: https://github.com/chaoticbob/Cinder-SdfText/commit/38633584d27f8913195717cc99e4091b4e6c58bd.
